### ISSUE TITLE
Can we apply language locale constants in the tabs?

### ISSUE THREAD

**Issue by cm-tigeen** [Jacobs63/vue3-tabs-component#12]
Can we apply language locale constants in the tabs?

**Comment by Jacobs63** [comment]
Hello,

would you elaborate your request?

I'm not really sure what do you mean, perhaps add a code example of what you're requesting.

**Comment by cm-tigeen** [comment]
Hi Jacobs,

Thanks for your quick reply. 

In my tabs object, i have different language constants & dropdown with language change option in the header component. I tried change language. It is not reflecting. Do you have any props to update data or header name?

![image](https://user-images.githubusercontent.com/77827545/162225981-7230ab2a-5ecc-406f-a2f5-f1db407cb1fd.png)

**Comment by Jacobs63** [comment]
@cm-tigeen 

This package provides a solution for working with tabs in Vue.
The tab component provides a simple solution for handling labels through the name prop - whether you set a tab's name statically or dynamically is on you to decide.

The issue you're experiencing is not related to the package itself, but rather to the project you're working on.


FYI: You can definitely pre-process the data you have and decide which object value should be passed as the tab's name prop based on the active language.

**Comment by cm-tigeen** [comment]
> ally is on you to decide

Hi Jacobs,

Update data using inject('updatetab'). But it is not working. I saw your code provide used in the tabs. Nothing working on it. 
https://vuejs.org/guide/components/provide-inject.html


![image](https://user-images.githubusercontent.com/77827545/162378477-e16626f4-d2d9-46d4-aa04-1e268087a0b4.png)
![image](https://user-images.githubusercontent.com/77827545/162378565-6ab2ec57-a640-40fa-89f8-8181364181da.png)

**Comment by Jacobs63** [comment]
@cm-tigeen 

You're clearly returning the variable `defaultSubcategoryName` every time, I still see no issue regarding the package.

**Comment by cm-tigeen** [comment]
Hi Jacobs,

Shared screenshot reverted to default header.  Now shared new screenshot. While changing language, function will return new header name. but it is not affecting dom. For second screenshot, how to work with inject update tab inside my function. 

![image](https://user-images.githubusercontent.com/77827545/162425292-4a7abb2b-90c7-4757-b382-d333bca7794a.png)
![image](https://user-images.githubusercontent.com/77827545/162425781-af3e4d2a-956c-4050-ab57-809b4341075c.png)

**Comment by Jacobs63** [comment]
@cm-tigeen 

Hello,

I can confirm that dynamically changing prefix, name & postfix props were not properly reflected in the tab's name.
Version 1.0.6 has been released which fixed this issue.


Thank you for clarifying what the issue was.

**Comment by cm-tigeen** [comment]
Hi Jacobs,

Thanks you very much to understand issue.
