### ISSUE TITLE
updateTab overwrites isActive state

### ISSUE THREAD

**Issue by roman-savuliak** [Jacobs63/vue3-tabs-component#13]
I have a dynamic suffix, which targets store state. Everytime it's updated - it triggers `updateTab` tabs method. The issue is, that `updateTab` does not have`isActive` property, so just after some milliseconds, when `selectTab` set `isActive` => it gets immediately overwritten with a data from `updateTab`, which does not have such property inside `data` argument.

Because of that issue tabs are loosing active state on every prefix/name/suffix dynamic update

```
updateTab(computedId, {
        name: props.name,
        header: props.prefix + props.name + props.suffix,
        isDisabled: props.isDisabled,
        hash: hash,
        index: tabsProvider.tabs.length,
        computedId: computedId
        // <--- no isActive property here
      })
```

My suggestion would be to "merge" data object, coming from updateTab with existing tab state, instead of replacement, cause it looks like `isActive` is the only property, not present there.

**Comment by Jacobs63** [comment]
Hello,

I agree on the fix - will take a look this week.

**Comment by Jacobs63** [comment]
Hello,

version 1.0.7 has been released which fixed this issue.
