### ISSUE TITLE
CDN or Unpkg

### ISSUE THREAD

**Issue by amchconsult** [Jacobs63/vue3-tabs-component#17]
Hi, can you compile or add Unpkg or JSDelivr. I am trying to use as global UMD on HTML and it is not working.

thank you

**Comment by ZsharE** [comment]
Same here.

@amchconsult you just need to download the repo and then:

```
npm install
npm run build
```

If you have any errors, just edit this line:
```
"build": "rm -rf dist && NODE_ENV=production webpack"
```
with this:
```
"build": "webpack"
```
And then:
```
npm run build
```

Then the dist folder will be created and the file index.js will run as a UMD. Rename it and done.

**Comment by Jacobs63** [comment]
UMD has been added in versions 1.0.9 which should fix this issue.
