### ISSUE TITLE
Inject/Provide + SSR

### ISSUE THREAD

**Issue by spacedawwwg** [Jacobs63/vue3-tabs-component#19]
I noticed there was a PR to add SSR support, but I can't seem to the `addTab` to work with SSR. 

The tabs `<ul>` empty and only populated on hydration. Is this by design?

**Comment by Jacobs63** [comment]
Hello,

yes, this is be design and there's no intention to change this.

Before mounting a `Tab` component it notifies the parent `Tabs` component that it should be added to the list.
