### ISSUE TITLE
Uncaught ReferenceError: n is not defined

### ISSUE THREAD

**Issue by Monologophobia** [Jacobs63/vue3-tabs-component#2]
When loading the component from https://cdn.jsdelivr.net/npm/vue3-tabs-component@1.0.1/src/index.js there is an additional "n" at the end of the first line which causes an error. I can't find where this is in the repo so no idea how it got on to the CDN file.

https://cdn.jsdelivr.net/npm/vue3-tabs-component@1.0.0/src/index.js is not affected (1.0.0 vs 1.0.1).

**Comment by Jacobs63** [comment]
Hello,

after investigating it seems like I've published the package before actually committing into the repo, which should not have happened in the first place.
Thus this trailing character unintentionally seems to have gotten published, which was a mistake on my side.

Version 1.0.2 has been released which fixed this issue.

Thank you for your contribution.
