### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by ruanspies** [Jacobs63/vue3-tabs-component#23]
I am trying to import the `vue3-tabs-component` in Vitepress but getting the error:

```
import { Tabs, Tab } from "vue3-tabs-component";
               ^^^
SyntaxError: Named export 'Tab' not found. The requested module 'vue3-tabs-component' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

My setup looks exactly the same as that of the demo [described here](https://github.com/vuejs/vitepress/issues/621#issuecomment-1122402597).

**Comment by Jacobs63** [comment]
Hello,

I am unable to reproduce this issue using the linked demo you've provided.
Could you create a repository/stackblitz with your setup?

**Comment by Monald** [comment]
I am also seeing this issue in Vitepress, the error only appears on build and not in dev.

`vitepress v1.0.0-alpha.49

✓ building client + server bundles...
build error:
file:///home/.../Documents/Repos/.../frontend/app/docs/.vitepress/.temp/app.js:3
import { Tabs, Tab } from "vue3-tabs-component";
               ^^^
SyntaxError: Named export 'Tab' not found. The requested module 'vue3-tabs-component' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue3-tabs-component';
const { Tabs, Tab } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (file:///home/.../Documents/Repos/.../frontend/app/node_modules/vitepress/dist/node/serve-4ba8f51b.js:42605:24)`

**Comment by Nuhel** [comment]
This issue Occur while ssr is enabled.

**Comment by Jacobs63** [comment]
Hello,

I'm not yet experienced with SSR and tried to reproduce this on Vitepress without any success.

If the issue still persists, please provide a better example of how to reproduce it.
