### ISSUE TITLE
pass text with html tag to tab component

### ISSUE THREAD

**Issue by bluelemonade** [Jacobs63/vue3-tabs-component#25]
Hi,

How can I put html tags to a tab

I tried  :html="selectedContent[currPage]"  Is the a method, property for this issue.

**Comment by Jacobs63** [comment]
Hello,

could you please elaborate on what you're trying to achieve?

To set a Tab's content, you can simply use it's default slot, which can contain anything you wish, including html:
```
    <tab name="Second tab">
      <h2 class="page-subtitle">Second tab</h2>
      This is the content of the second tab.
    </tab>
```

**Comment by bluelemonade** [comment]
i tried to pass text with html tags via {{  }}. ok tjats. wrong. I have to use html="variable". bit. thats not working.

**Comment by Jacobs63** [comment]
Hello,

please post a demo with your code, as I unfortunately still do not understand what the issue is.

**Comment by bluelemonade** [comment]
I reinstalled the component and now the v-html works. hmmm
