### ISSUE TITLE
useUrlFragment and disableScrollBehavior dont work together

### ISSUE THREAD

**Issue by PiedadeJoao** [Jacobs63/vue3-tabs-component#26]
Hello :)
When send by props the useUrlFragment: true and disableScrollBehavior: true the query param is not added to the URL.
So the expect behaviour should be update the url with the query param and not scroll.

**Comment by PiedadeJoao** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/55803588/200309105-03acb06d-49bf-4d7b-a7fc-10e795b70d6e.png">

The problem is that if you do the event.preventDefault() here it will block the :href on the element <a/> so will not update the url. Maybe the solution for that is to add an exception when disableScrollBehavior is true to update the href through javascript. window.location.href = "" this will not reload the page

**Comment by heartdriven** [comment]
Same issue here.  It's a bit counterintuitive that these options do not work together.

**Comment by heartdriven** [comment]
Also, if you set useUrlFragment or disableScrollBehavior, it will also stop the @changed or @clicked events from being executed...
