### ISSUE TITLE
Customizing the Tab

### ISSUE THREAD

**Issue by shimcup** [Jacobs63/vue3-tabs-component#27]
Hello,

I was wondering if there was a way to customize the "tab" element.

We would like to have an image tag as part of the tag, but it seems like it can't be passed through as part of the element.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/49737086/203112434-b8c6220d-044c-4b79-95b6-db53a6ae50f1.png">

Please assist and let me know if I can provide additional information.

Thanks,
Simon

**Comment by Maqsyo** [comment]
you could use a prefix and suffix for this
```html
<tab 
    prefix="<span class='glyphicon glyphicon-star'></span>" 
    name="Prefix and suffix" 
    suffix="<span class='badge'>4</span>"
>
    A prefix and a suffix can be added
</tab>
```

**Comment by Jacobs63** [comment]
The solution provided by @Maqsyo is what you should be using - custom prefixes and suffixes.

**Comment by ghost** [comment]
What if i not need any string name in tab, but only my own icons. 
How can i hide string name?
