### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by mesqueeb** [Jacobs63/vue3-tabs-component#3]
Would love a demo site so I can play around with it before I decide if I wanna install the library or not. : )

**Comment by Jacobs63** [comment]
Hello,

I'll see what I can do about it, thank you for the suggestion.

**Comment by Jacobs63** [comment]
I've prepared a demo on [my site](https://tabs-component.jakubpotocky.sk/) updating the original demo made by Spatie.

**Comment by mesqueeb** [comment]
Nice!! Looking good : )

**Comment by acrolink** [comment]
@Jacobs63 

Thanks for sharing, the `css` is great. I see that the library ships with no styles, but the demo you provided helped me.

**Comment by dzikoysk** [comment]
Link to the demo is not valid anymore, might be a good idea to update this and link in the README :)

**Comment by Jacobs63** [comment]
@dzikoysk 

The demo has now been rewritten to use WebPack 5 & a link has been added to README.

Sorry for the downtime - I was moving server hosting.
