### ISSUE TITLE
Typescript support required !

### ISSUE THREAD

**Issue by SurajMazar** [Jacobs63/vue3-tabs-component#30]
![image](https://user-images.githubusercontent.com/49373020/213998200-2fbaa28b-5ad3-4e8d-86b5-3875066e8fc7.png)

**Comment by YehorPytomets** [comment]
@SurajMazar, what exactly does the error say?

**Comment by YehorPytomets** [comment]
@Jacobs63, I'm not sure if it is related to SurajMazar's problem, but it seems that in `1.1.3` the `dist` folder disappears from `node_modules`. I don't have this problem with `1.1.0` and `1.1.2`.
Node: v16.19.0
NPM: 8.19.3

**Comment by Jacobs63** [comment]
> @Jacobs63, I'm not sure if it is related to SurajMazar's problem, but it seems that in `1.1.3` the `dist` folder disappears from `node_modules`. I don't have this problem with `1.1.0` and `1.1.2`. Node: v16.19.0 NPM: 8.19.3

My bad - forgot to publish the compiled files 🤦

**Comment by YehorPytomets** [comment]
@Jacobs63, solved with `1.1.4`, thank you 👍

**Comment by SurajMazar** [comment]
@Jacobs63  well i m using vue with typescript , and when i import the components from the library , as there is no  type definitions  we get the following error

hence 
![image](https://user-images.githubusercontent.com/49373020/214652619-fd93d088-13aa-4170-8144-3dead9ee7e27.png)

**Comment by SurajMazar** [comment]
@Jacobs63 when i use the library with plain js or ignore the warning (while working with ts) it works fine . but i think its nice to have a type definition for typescript support.

**Comment by Jacobs63** [comment]
Hello,

version 1.3.0 now includes the package fully rewritten in TypeScript.

**Comment by januarfonti** [comment]
Hi @Jacobs63 , I'm using Nuxt 3 & "vue3-tabs-component": "^1.3.7",

But I'm still got this error when importing the component
<img width="654" alt="Screenshot 2024-05-16 at 21 53 35" src="https://github.com/Jacobs63/vue3-tabs-component/assets/5006571/d788d1aa-e5e9-4fdd-8e3e-b1c4566b4284">
