### ISSUE TITLE
Css file not found in node_modules

### ISSUE THREAD

**Issue by AndrianD** [Jacobs63/vue3-tabs-component#32]
Hello Jacobs63,
Nice plugin thank you, but did you forget to upload the css file in the node_modules package? because I don't see it [there](https://www.npmjs.com/package/vue3-tabs-component?activeTab=explore), and yet its present  in this github repo under `./docs/resources/` 
Thank you for your reply

**Comment by Jacobs63** [comment]
Hello,

CSS is not part of the package, as it is undesired - most CSS frameworks include tabs.

The docs are just an example implementation - you're free to copy the styles from the css file in the repository if you'd like to.
It will not be a part of the published package, as the package is not dependent on the demo, but vice-versa.
