### ISSUE TITLE
Aria-controls contains wrong ID

### ISSUE THREAD

**Issue by heartdriven** [Jacobs63/vue3-tabs-component#34]
Thanks for this plugin, it's very useful to me and my project. However, there is one accessibility issue that caught my attention, and it's that the 'aria-controls' attribute in Tabs.vue contains the wrong value.  Currently, it contains the same value as the href field: a value prepended with a # sign (computed in Tab.vue).  However, according to the spec, the aria-controls attribute should contain the id of the element it controls (and not the selector in this case).  It would be very helpful if this would get fixed.

Thanks!

**Comment by Jacobs63** [comment]
Thank you for the heads up & the contribution.
Version 1.2.1 has been released which contains the fix.
