### ISSUE TITLE
No obvious way to disable caching

### ISSUE THREAD

**Issue by lupinitylabs** [Jacobs63/vue3-tabs-component#36]
The README reads:

> When disabling the cache, it can be useful to specify a default tab to load which is not the first one. You can select this by passing the defaultTabHash option.

However, there is no documentation on how to actually disable the cache. Setting `cache-lifetime` to 0 does not work (it is still cached, even if it instantly expires). Examining the code, it does not seem that any option exists to control the caching feature - on each change, it is just getting stored.

I am happy to contribute a PR for this feature, either not caching if cache-lifetime is zero, or having a separate cache option - whatever you prefer.

**Comment by Jacobs63** [comment]
Hello,

I agree with the proposed solution that setting the `cache-lifetime` prop to `0` should disable the cache.
Version 1.3.1 has been released which contains this change.
