### ISSUE TITLE
Ability to prevent opening an another tab.

### ISSUE THREAD

**Issue by fork88888** [Jacobs63/vue3-tabs-component#37]
Hi, thanks for this nice component!

I faced with a task where is a need to prevent opening a new tab if data at previous one was not saved. I can inform the user that data is not saved using "changed" or "click" events but I can prevent the opening of another tab.
I looked at the code but it seems that this ability is not avalible. Or maybe its possible some way?

**Comment by Jacobs63** [comment]
Hello,

I believe you should be able to set the tab as disabled via the `is-disabled` prop, which reacts to real-time changes from outside, so you could set/toggle the disabled state and prevent the user from opening it.

Handling whether the tab should be disabled or not is something you should handle in your application.
