### ISSUE TITLE
Order of tabs is not respected

### ISSUE THREAD

**Issue by ghost** [Jacobs63/vue3-tabs-component#38]
I have a set of tabs and they are in this order
1
2
3
4
5

When I refresh then the order changes to 
1
3
4
5
2

No matter how many times I change the order of the tabs if I refresh the one specific tab always goes to the end. What determines the order and how can I set a specif order that will stay that way?

**Comment by Jacobs63** [comment]
Hello,

the order of tabs should not change.

Without seeing the code it is hard to find the reason.
I'd suggest making sure that you're not missing a key in case youre creating those tabs in a v-for loop.

**Comment by Jacobs63** [comment]
Closing due to no response from the author.
