### ISSUE TITLE
Rollup failed to resolve import "vue3-Tabs-component"

### ISSUE THREAD

**Issue by sohilpro** [Jacobs63/vue3-tabs-component#39]
how can i fix this in nuxt3?

[vite]: Rollup failed to resolve import "vue3-Tabs-component" from "/app/components/Product/TabProduct.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

**Comment by Jacobs63** [comment]
You have an invalid package name. The T in "vue3-Tabs-component" should not be uppercase.

**Comment by Jacobs63** [comment]
Closed as the issue was likely fixed by the author.
