### ISSUE TITLE
event is undefined

### ISSUE THREAD

**Issue by bellerstefan** [Jacobs63/vue3-tabs-component#4]
Hi, I experienced a little bug while using this component

![image](https://user-images.githubusercontent.com/16673073/127365253-a7af47a8-6204-494c-a202-b7a7dfd3d541.png)

The event is undefined when called and the first tab is disabled

https://github.com/Jacobs63/vue3-tabs-component/blob/fa534e6473086afc6afcd3180a7d1439d551a0f9/src/components/Tabs.vue#L106

a solution to the problem could be

`event !== undefined && event.preventDefault();`

or something like that - maybe there is a better way ?

Thank you :)

**Comment by Jacobs63** [comment]
Hello,

yes, as the function is used on various places there has to be a check for the event being provided as a parameter.

Version 1.0.3 has been released which fixed this issue.

Thank you for your contribution.
