### ISSUE TITLE
focus on click goes to body, but should remain on current tab element

### ISSUE THREAD

**Issue by plweil** [Jacobs63/vue3-tabs-component#40]
When I click on a tab element in this component, the focus is always going to `<body>`. I don't think this is what you intended.

It's my understanding that when a tab element is clicked, the focus should remain on that element. This is how [Heydon's tabs](https://codepen.io/heydon/pen/veeaEa/) work. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role), 

> Tabs do not act as anchor links to individual panels — and upon activation, keyboard focus should remain on the current tab element and not automatically move to the newly displayed tabpanel.

To accomplish this, all you might have to do is add `tabindex="-1"` to each tab element. e.g., 

```html
<ul role="tablist" class="tabs-component-tabs">
<li class="tabs-component-tab is-inactive" role="presentation">
<a role="tab" tabindex="-1" class="tabs-component-tab-a is-inactive" aria-controls="tab-project-pane" aria-selected="false" href="#tab-project">Projects</a>
</li>
<li class="tabs-component-tab is-active" role="presentation">
<a role="tab" tabindex="-1" class="tabs-component-tab-a is-active" aria-controls="tab-profile-pane" aria-selected="true" href="#tab-profile">Profile</a>
</li>
<li>[another tab]</li>
<li>[another tab]</li>
</ul>
```

**Comment by Jacobs63** [comment]
Hello,

thank you for the report, version 1.3.3 has been released which fixes this issue.
