### ISSUE TITLE
Select default tab without cache lifetime not possible

### ISSUE THREAD

**Issue by cn42** [Jacobs63/vue3-tabs-component#46]
Is it possible to change the component to be able to set the default tab at start independently?
Now it only works if the cache lifetime is set and active.

Here I found the code to change:
https://github.com/Jacobs63/vue3-tabs-component/blob/c36b42bac25c8e4da2e7e7fe4bdaa86d95043fa4/src/components/Tabs.vue#L201-L213

**Comment by Jacobs63** [comment]
Hello,

latest version 1.3.7 fixes this issue, as I believe setting the default tab hash should be a fallback (if specified) regardless of whether the cache is enabled or not.
