### ISSUE TITLE
Executing Tab's onMounted When Clicked

### ISSUE THREAD

**Issue by naumanzchaudhry** [Jacobs63/vue3-tabs-component#49]
I have tabs which depend on data from previous tab. Previous tab's data is pushed to the backend. Next tab fetches that updated data from backend in onMount. 

I'd like to have onMount run when tab is clicked. Also, can I enforce that it doesn't run onMount for each tab on initial load?

**Comment by naumanzchaudhry** [comment]
I just found [this article](https://michaelnthiessen.com/force-re-render/) which solves the re-render on tab click for me. I am now using `:key` binding and changing the key on `@changed` events of tabs. And now it re renders.

But I'd like to stop calling onMount for each tab on initial setup.

**Comment by Jacobs63** [comment]
Hello,

you cannot prevent the `onBeforeMount` hook as it ensure the `Tabs` component knows about the child `Tab` components that are in its slot, as it calls the provided `addTab` method on the parent `Tabs` component.
Without that, you wouldn't even have a tab to click on in the tabs navigation.

**Comment by naumanzchaudhry** [comment]
@Jacobs63 got it. thanks!
