### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by john-** [Jacobs63/vue3-tabs-component#5]
This probably has nothing to do with this tab component and is probably basic html/css stuff.

I am using the sample code from the README.md:
```
<div>
    <tabs>
        <tab name="First tab">
            First tab content
        </tab>
        <tab name="Second tab">
            Second tab content
        </tab>
        <tab name="Third tab">
            Third tab content
        </tab>
    </tabs>
</div>
```
When rendered in the browser, it looks like this:
![vue3_tab_component](https://user-images.githubusercontent.com/2359125/129452572-59268fef-d096-40fb-922a-5d54543ebaa1.png)
The tabs function as expected.  However, how do I get it to display as a row of tabs on a single line?   Is this done with CSS?  If there is an example of how to do this it would be appreciated.

**Comment by Jacobs63** [comment]
Hello,

flexbox could be an elegant solution for styling the tabs header.


I'm currently working on a demo for the package, which will contain example styles aswell.

**Comment by john-** [comment]
Thanks.  I will take a look at flex box.
