### ISSUE TITLE
Tabs are not updating

### ISSUE THREAD

**Issue by PabloFacciano** [Jacobs63/vue3-tabs-component#6]
Suppose I have something like this:
``` vue
<tabs :options="{ useUrlFragment: true }">
  <tab v-for="tab in this.$store.state.tabs" :key="tab.id" :name="tab.name" :id="tab.id">
    <component-a v-if="tab.type == 'a'" />
    <component-b v-if="tab.type == 'b'" />
  </tab>
</tabs>
```
When I modify the open tabs `$store.state.tabs` and remove an item, nothing happens with the tabs components.

Within my humble opinion (and I may be wrong), I think a `beforeUnmount hook` may be missing that removes the tab from the internal state of the tabs component.

At the moment, the only workaround is to [reload the tabs component](https://michaelnthiessen.com/force-re-render/).

**Comment by Jacobs63** [comment]
Hello,

after investigating I can confirm that removing a child Tab component was not reflected in the parent's internal state.
Thus adding an `onBeforeUnmount` hook, which removes it from the Tabs component's internal state is a correct approach.

Version 1.0.4 has been released which fixed this issue.

Thank you for your contribution.
