### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by fvanwijk** [Jacobs63/vue3-tabs-component#7]
If I want to use this package in a Vue3 TS project, I get an error on `import { Tabs, Tab } from 'vue3-tabs-component';` stating that the type definitions are missing.
This is absolutely correct.

Would it be possible to add type definitions to this package?

**Comment by sunil-dzango** [comment]
I am having the same issue. Can't use this with Typescript. Have you found other alternatives?

**Comment by Jacobs63** [comment]
Hello,

I have a types files in the works, however, as I'm learning TypeScript myself, it takes a bit to find the correct solution.

If anyone is more experienced, I'll be happy to merge a pull request containing all the required changes for TS support.

**Comment by Jacobs63** [comment]
Hello,

version 1.3.0 now includes the package fully rewritten in TypeScript.
